---
title: "Master"
output:
  pdf_document: default
  html_document: default
---
A number of viables are defined,
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```


```{r "Second model exercise 5, simulate data, find MLE, test beta = 1"}
n <- 500                
x_icount <- 10        # How many x and y there is 
x_i <- 1:x_icount
# x_icount <- 10 - 3
# x_i <- c(1:3,rep(2,x_icount))
a_nul <- 0
beta_nul <- 1
gamma_nul <- 0
conff1b <- matrix(nrow=n, ncol=2)
conff1a <- matrix(nrow=n, ncol=2)
limits <- rep(0,n)
errors <- rep(0,n)
betahat <- rep(0,n)
ahat <- rep(0,n)
resulthypotese_ab <- rep(0,n)
bstar <- 1.1
crit = pchisq(0.05,df=2,lower.tail = FALSE)
beta <- function(b,c1 = 1,c2 = 0) {
  b ^ (c1 * x_i + c2)
}
for (ii in 1:n) {
  yi <- rnorm(x_icount, mean=0, sd=1)
  likelihood <- function(a,b) {
    1 / sqrt(2*pi)^x_icount * prod(exp ((- (a * b ^x_i + yi)^2)/2))
  }
  
  s <- function(b) {
    a <- sum(yi)/sum(beta(b,1,0))
    - sum( a^2 * beta(b,2,-1) * x_i)  +  sum(a * x_i * beta(b,1,-1) * yi)
  }
  
  i <- function(b) {
    a <- sum(yi)/sum(beta(b,1))
    ma <- sum(a ^ 2 * 2 * (x_i-1) * beta(b,2,-2) * x_i)-sum(a ^ 2 * x_i * (x_i-1) * beta(b,2,-2))
    ma^(-1)
  }
  
  intim <- function(b, funk1, funk2) {
    score <- funk1 
    fish <- funk2 
    bk <- b
    itt <-0
    itt1 <- 0
    itt2 <- 0 
    while(abs(score(bk) * fish(bk))>0.001) {
      itt<- itt + 1
      bk = bk + fish(bk) * score(bk)
      if (!is.finite(score(bk))==TRUE | !is.finite((fish(bk)))==TRUE) {
        cat("ERROR!", "\n")
        itt2 <- 1
        break
      }
      if (itt>5000) {
        cat("break", "\n")
        itt1 <- 1
        break(intim)
      }
    }
    c(bk,itt, itt1, itt2)
  }
  resultatintim <- intim(bstar, s, i)
  betahat[ii] <-  resultatintim[1] 
  ahat[ii] <- sum(yi)/sum(beta(betahat[ii],1,0))
  lmle <- likelihood(ahat[ii],betahat[ii])
  
  lognorm <- function(a,b) {
    -2*log(likelihood(a,b)/lmle)
  }
  
  resulthypotese_ab[ii] <- lognorm(a_nul, beta_nul)<=crit
  j11y <- 1 / (sum(beta(betahat[ii],2,0)))
  j22y <- 1 / (sum(ahat[ii] * (2 * x_i - 1) * beta(betahat[ii],2,-1) * x_i) 
               -sum(ahat[ii] * x_i *(x_i - 1)* beta(betahat[ii], 1, 0 ) * yi))
  conff1b[ii,1] <- betahat[ii] - 1.96 * sqrt(abs(j22y))
  conff1b[ii,2] <- betahat[ii] + 1.96 * sqrt(abs(j22y))
  conff1a[ii,1] <- ahat[ii] - 1.96 * sqrt(abs(j11y))
  conff1a[ii,2] <- ahat[ii] + 1.96 * sqrt(abs(j11y))
  limits[ii] <- resultatintim[3]
  errors[ii] <- resultatintim[4]
  cat("Iteration=", ii, "Limits=", sum(limits),  "Errors=",sum(errors) , "\n") 
}
cat("How many times did alpha0 end inside the confidence interval", "\n")
confresula <- which(conff1a[,1] < a_nul & conff1a[,2] > a_nul)
length(confresula)
cat("How many times did beta0 end inside the confidence interval", "\n")
confresulb <- which(conff1b[,1] < beta_nul & conff1b[,2] > beta_nul)
length(confresulb)
cat("How many was m2lognorm less or equal to the critical values", "\n")
sum(resulthypotese_ab)
```



```{r "repeat 500 times"}
ahat_plot <- data.frame(x=1:n, y= ahat)
betahat_plot <- data.frame(x=1:n, y= betahat)
ahat_betahat <- data.frame(x= ahat, y=betahat)
ggplot(ahat_plot, aes(x,y)) +
  geom_point() + 
  scale_y_continuous(limits=c(-1,1)) + 
  labs(x = "index", y= "alpha")
ggplot(betahat_plot, aes(x,y)) +
  geom_point() +
  scale_y_continuous(limits=c(0,5)) +
  labs(x = "index", y= "beta")
ggplot(ahat_betahat, aes(x,y)) +
  geom_point(size = 0.7) + 
  scale_y_continuous(limits=c(0.6,2.5)) +
  scale_x_continuous(limits=c(-0.8,0.8)) + 
  labs(x = "alpha", y= "beta")
```



```{r "exercise 2.5.1, model 2 v 3, MLE with Newton-Raphson, MLE with optim"}
x_icount <- 20
n <- 1
x_i <- 1:x_icount
beta_nul <- 1
gamma_nul <-0
p_waldtest_g <- rep(0,n)
conff1g <- matrix(nrow=1, ncol=2)
betahat <- rep(0,n)
ahat <- rep(0,n)
gammahat <- rep(0,n)
resulthypotese <- rep(0,n)
bstar <- 1.1
crit = pchisq(0.05,df=3,lower.tail = FALSE)
beta <- function(b,c1 = 1,c2 = 0) {
  b ^ (c1 * x_i + c2)
}

yi <- c(-0.8, 1.15, 1.82, 2.89, 1.43, 0.59, 1.09, 3.00, 2.81, 3.02, 2.39, 3.50, 3.06, 2.41, 2.81, 3.95, 4.19, 5.94, 7.06, 4.55)
likelihood <- function(a,b,g) {
  1 / sqrt(2*pi)^x_icount * prod(exp(( - (a * b ^x_i -yi + g)^2)/2))
}

s <- function(b) {
  a_s <- sum(beta(b))
  b_s <- (sum(beta(b))) / n * sum(beta(b)) 
  c_s <- (sum(beta(b))) / n * sum(yi)
  d_s <- sum(yi*beta(b))
  sahat <- (c_s-d_s)/(b_s-a_s)
  gamma <- 1 / n * sum(sahat*beta(b)-yi) 
  - sum((sahat * beta(b) + gamma - yi ) * beta(b,1,-1) * x_i* sahat)
}

i <- function(b) {
  a_s <- sum(beta(b))
  b_s <- (sum(beta(b))) / n * sum(beta(b)) 
  c_s <- (sum(beta(b))) / n * sum(yi)
  d_s <- sum(yi*beta(b))
  sahat <- (c_s-d_s)/(b_s-a_s)
  gamma <- 1 / n * sum(sahat*beta(b))- sum(yi) 
  imi <- sum(x_i * sahat * beta(b,1,-2) * ((2*x_i-1) * sahat *beta(b) + 
                                             gamma * (x_i-1) - ((sahat * beta(b) + gamma)) *(x_i -1)  ))
  imi^-1
}

intim <- function(b, funk1, funk2) {
  score <- funk1 
  fish <- funk2 
  bk <- b
  itt <-0
  itt1 <- 0
  itt2 <- 0 
  while(abs(score(bk) * fish(bk))>0.001) {
    itt<- itt + 1
    bk = bk + fish(bk) * score(bk)
    if (!is.finite(score(bk))==TRUE | !is.finite((fish(bk)))==TRUE) {
      cat("ERROR!", "\n")
      itt2 <- 1
      break
    }
    if (itt>5000) {
      cat("break", "\n")
      itt1 <- 1
      break(intim)
    }
  }
  c(bk,itt, itt1, itt2)
}
resultatintim <- intim(bstar, s, i)
betahat <-  resultatintim[1] 
ahat_s <- sum(beta(betahat))
bhat_s <- (sum(beta(betahat))) / n * sum(beta(betahat)) 
chat_s <- (sum(beta(betahat))) / n * sum(yi)
dhat_s <- sum(yi*beta(betahat))
ahat <- (chat_s-dhat_s)/(bhat_s-ahat_s)
gammahat <- 1 / n * sum(ahat*beta(betahat))- sum(yi)
lmle <- likelihood(ahat,betahat, gammahat)
lognorm <- function(a,b,g) {
  -2*log(likelihood(a,b,g)/lmle)
}

resulthypotese <- lognorm(ahat, betahat, gamma_nul)<=crit 
j33y <- 1 / x_icount
waldtestg <- (gammahat-gamma_nul)^2/ j33y
p_waldtest_g <- 2*pnorm(abs(waldtestg), lower.tail = FALSE)

conff1g[,1] <- gammahat - 1.96 * sqrt(abs(j33y))
conff1g[,2] <- gammahat + 1.96 * sqrt(abs(j33y))
cat("Was gamma0 inside the confidence interval", "\n")
confresulg <- which(conff1g[,1] < gamma_nul & conff1g[,2] > gamma_nul) 
length(confresulg)
cat("Did gamma0 pass the waldtest?", "\n")
p_waldtest_g>=0.05
cat("Was n2lognorm less than the critical value?", "\n")
sum(resulthypotese)
Param_NR <- c(ahat*betahat^x_i+gammahat)


```


```{r}

likelihood_v <- function(abg) {
  1 / sqrt(2*pi)^x_icount * prod(exp((- (abg[1] * abg[2]^x_i +abg[3]  -yi)^2)/2))
}
param_optim <- optim(c(0,1,0), likelihood_v)$par
lmle_optim <- likelihood(param_optim[1],param_optim[2], param_optim[3])

lognorm_optim <- function(a,b,g) {
  -2*log(likelihood(a,b,g)/lmle_optim)
}

resulthypotese_optim <- lognorm_optim(param_optim[1], param_optim[2], gamma_nul)<=crit 
waldtestg_optim <- (param_optim[3]-gamma_nul)^2/ j33y
p_waldtest_g_optim <- 2*pnorm(abs(waldtestg_optim), lower.tail = FALSE)
conff1g_optim <- matrix(nrow=1, ncol=2)
conff1g_optim[,1] <- param_optim[3] - 1.96 * sqrt(abs(j33y))
conff1g_optim[,2] <- param_optim[3] + 1.96 * sqrt(abs(j33y))
cat("Was gamma0 inside the confidence interval", "\n")
confresulg_optim <- which(conff1g_optim[,1] < gamma_nul & conff1g_optim[,2] > gamma_nul) 
length(confresulg_optim)
cat("Did gamma0 pass the waldtest?", "\n")
p_waldtest_g_optim>=0.05
cat("Was n2lognorm less than the critical value?", "\n")
sum(resulthypotese_optim)
```


```{r "exercise 2.5.1, model 1 v 2, MLE with Newton-Raphson, MLE with optim"}
x_icount <- 20
n <- 1
x_i <- 1:20
a_nul <- 0
beta_nul <- 1
p_waldtest_b <- rep(0,n)
conff1b <- matrix(nrow=n, ncol=2)
betahat <- rep(0,n)
ahat <- rep(0,n)
bstar <- 2
resulthypotese <- rep(0,n)
crit = pchisq(0.05,df=2,lower.tail = FALSE)
beta <- function(b,c1,c2 = 0) {
  b ^ (c1 * x_i + c2)
}

yi <- c(-0.8, 1.15, 1.82, 2.89, 1.43, 0.59, 1.09, 3.00, 2.81, 3.02, 2.39, 3.50, 3.06, 2.41, 2.81, 3.95, 4.19, 5.94, 7.06, 4.55)
likelihood <- function(a,b) {
  1 / sqrt(2*pi)^x_icount * prod(exp((- (a * b ^x_i -yi)^2)/2))
}

s <- function(b) {
  a <- sum(yi)/sum(beta(b,1,0))
  - sum( a^2 * beta(b,2,-1) * x_i)  +  sum(a * x_i * beta(b,1,-1) * yi)
}

i <- function(b) {
  a <- sum(yi)/sum(beta(b,1))
  ma <- sum(a ^ 2 * 2 * (x_i-1) * beta(b,2,-2) * x_i)-sum(a ^ 2 * x_i * (x_i-1) * beta(b,2,-2))
  ma^(-1)
}

intim <- function(b, funk1, funk2) {
  score <- funk1 
  fish <- funk2 
  bk <- b
  itt <-0
  itt1 <- 0
  itt2 <- 0 
  while(abs(score(bk) * fish(bk))>0.001) {
    itt<- itt + 1
    bk = bk + fish(bk) * score(bk)
    if (!is.finite(score(bk))==TRUE | !is.finite((fish(bk)))==TRUE) {
      cat("ERROR!", "\n")
      itt2 <- 1
      break
    }
    if (itt>5000) {
      cat("break", "\n")
      itt1 <- 1
      break(intim)
    }
  }
  c(bk,itt, itt1, itt2)
}
resultatintim <- intim(bstar, s, i)
betahat <-  resultatintim[1] 
ahat <- sum(yi)/sum(beta(betahat,1,0))
lmle <- likelihood(ahat,betahat)

lognorm <- function(a,b) {
  -2*log(likelihood(a,b)/lmle)
}

resulthypotese <- lognorm(ahat, beta_nul)<=crit #Alpha afhænger af beta, beta_nul indsættes 
j22y <- 1 / (sum(ahat * (2 * x_i - 1) * beta(betahat,2,-1) * x_i) -
               sum(ahat * x_i *(x_i - 1)* beta(betahat, 1, 0 ) * yi))
waldtestb <- (betahat-beta_nul) ^ 2 / j22y
p_waldtest_b <- 2*pnorm(abs(waldtestb), lower.tail = FALSE)
conff1b[,1] <- betahat - 1.96 * sqrt(abs(j22y))
conff1b[,2] <- betahat + 1.96 * sqrt(abs(j22y))
cat("Was beta0 inside the confidence interval", "\n")
confresulb <- which(conff1b[,1] < beta_nul & conff1b[,2] > beta_nul) 
length(confresulb)
cat("Did beta0 pass the waldtest?", "\n")
p_waldtest_b>=0.05
cat("Was n2lognorm less than the critical value?", "\n")
sum(resulthypotese)



```


```{r}

likelihood_v <- function(ab) {
  1 / sqrt(2*pi)^x_icount * prod(exp((- (ab[1] * ab[2]^x_i -yi)^2)/2))
}
param_optim <- optim(c(0.5,2), likelihood_v)$par
lmle_optim <- likelihood(param_optim[1],param_optim[2])

lognorm_optim <- function(ab) {
  -2*log(likelihood_v(ab)/lmle_optim)
}



resulthypotese_optim <- lognorm_optim(c(param_optim[1], beta_nul))<=crit 
j22y <- 1 / (sum(param_optim[1] * (2 * x_i - 1) * beta(param_optim[2],2,-1) * x_i) -
               sum(param_optim[1] * x_i *(x_i - 1)* beta(param_optim[2], 1, 0 ) * yi))
waldtestb_optim <- (param_optim[2]-beta_nul)^2/ j22y
p_waldtest_b_optim <- 2*pnorm(abs(waldtestb_optim), lower.tail = FALSE)
conff1b_optim <- matrix(nrow=1, ncol=2)
conff1b_optim[,1] <- param_optim[2] - 1.96 * sqrt(abs(j22y))
conff1b_optim[,2] <- param_optim[2] + 1.96 * sqrt(abs(j22y))
cat("Was beta0 inside the confidence interval", "\n")
confresulb_optim <- which(conff1b_optim[,1] < beta_nul & conff1b_optim[,2] > beta_nul) 
length(confresulb_optim)
cat("Did beta0 pass the waldtest?", "\n")
p_waldtest_b_optim>=0.05
cat("Was n2lognorm less than the critical value?", "\n")
sum(resulthypotese_optim)

```



```{r "exercise 2.5.2, specify parameters, plot data v fitted mean, plot linear regression"}

```


